FROM node:23-alpine3.20 AS builder

WORKDIR /app

COPY package*.json ./
RUN npm install --production=false

COPY . .

RUN npm run build

FROM scratch

COPY --from=builder /app/dist /app/dist

CMD ["/bin/true"]
