FROM node:23-alpine3.20 AS base

ARG VITE_PUBLIC_API_URL
ENV VITE_PUBLIC_API_URL=$VITE_PUBLIC_API_URL

RUN apk add --no-cache g++ make py3-pip libc6-compat curl

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN chmod -R 755 /app

CMD ["npm", "run", "dev"]
