FROM node:23-alpine3.20 AS base

RUN apk add --no-cache g++ make py3-pip libc6-compat nginx curl

RUN addgroup -S appgroup && adduser -S appuser -G appgroup

WORKDIR /app

COPY package*.json ./

RUN npm ci 

COPY . .

RUN chmod -R 755 /app

RUN chown -R appuser:appgroup /app

USER appuser

COPY ./build/nginx-dev.conf /etc/nginx/http.d/default.conf

CMD ["sh", "-c", "nginx && npm run dev"]

EXPOSE 80