networks:
  database-backend-bridge:
    driver: bridge
  backend-frontend-bridge:
    driver: bridge
  ollama-backend-bridge:
    driver: bridge

volumes:
  postgres-data-prod:
  uploads-data-prod:
  ollama-data-prod:
  matomo-data-prod:
  node-modules-prod:
  mercure-data-prod:
  mercure-config-prod:

services:
  #postgres database
  database:
    image: postgres:17.4-alpine
    container_name: postgres_quiz
    environment:
      POSTGRES_USER: ${POSTGRES_USER_PROD}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_PROD}
      POSTGRES_DB: ${POSTGRES_DB_PROD}
    volumes:
      - postgres-data-prod:/var/lib/postgresql/data:rw
    networks:
      - database-backend-bridge
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB:-database}", "-U", "${POSTGRES_USER:-user}"]
      timeout: 5s
      retries: 5
      start_period: 60s

  #backend - symfony
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
      args:
        DATABASE_URL: ${DATABASE_URL_PROD}
    ports:
      - "8000:443"
    container_name: backend_quiz
    environment:
      APP_ENV: prod
      APP_DEBUG: 1
      SHELL_VERBOSITY: 3
      APP_SECRET: ${APP_SECRET_PROD}
      CORS_ALLOW_ORIGIN: ${SYMFONY_CORS_ALLOW_ORIGIN}
      DATABASE_URL: ${DATABASE_URL_PROD}
      JWT_PASSPHRASE: ${SYMFONY_JWT_PASSPHRASE}
      SPEC_SHAPER_ENCRYPT_KEY: ${SPEC_SHAPER_ENCRYPT_KEY}
      MERCURE_URL: ${MERCURE_URL}
      MERCURE_JWT_SECRET: ${MERCURE_JWT_KEY}
      JWT_COOKIE_SECURE: TRUE
    volumes:
      - ./backend:/app:delegated
      - uploads-data-prod:/app/public/uploads/images
    depends_on:
      - database
    networks:
      - database-backend-bridge
      - backend-frontend-bridge
      - ollama-backend-bridge

  #frontend - vuejs
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - "443:443"
    volumes:
      - ./frontend:/app:delegated
      - node-modules-prod:/app/node_modules
    container_name: frontend_quiz
    depends_on:
      - backend
    environment:
      NODE_ENV: prodelopment
      VITE_PUBLIC_API_URL: ${VITE_PUBLIC_API_URL}
      VITE_PUBLIC_IMAGES_URL: ${VITE_PUBLIC_IMAGES_URL}
      VITE_PUBLIC_PFP_URL: ${VITE_PUBLIC_PFP_URL}
      MERCURE_PUBLIC_URL: ${MERCURE_PUBLIC_URL}
      PATH: /app/node_modules/.bin:$PATH

      WATCHPACK_POLLING: true
    networks:
      - backend-frontend-bridge

  #ollama - ai
  ollama:
    image: ollama/ollama:latest
    container_name: ollama_quiz
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama-data-prod:/root/.ollama
    networks:
      - ollama-backend-bridge

  #matomo - analytics
  matomo:
    image: matomo:latest
    container_name: matomo_quiz
    restart: unless-stopped
    depends_on:
      - database
    environment:
      MATOMO_DATABASE_HOST: database
      MATOMO_DATABASE_ADAPTER: postgres
      MATOMO_DATABASE_TABLES_PREFIX: matomo_
      MATOMO_DATABASE_USERNAME: ${POSTGRES_USER_PROD}
      MATOMO_DATABASE_PASSWORD: ${POSTGRES_PASSWORD_PROD}
      MATOMO_DATABASE_DBNAME: matomo
    ports:
      - "8081:443"
    volumes:
      - matomo-data-prod:/var/www/html
    networks:
      - backend-frontend-bridge
      - database-backend-bridge

  mercure:
    image: dunglas/mercure
    container_name: mercure_quiz
    restart: unless-stopped
    environment:
      SERVER_NAME: ':80'
      MERCURE_PUBLISHER_JWT_KEY: ${MERCURE_JWT_KEY}
      MERCURE_SUBSCRIBER_JWT_KEY: ${MERCURE_JWT_KEY}
      MERCURE_EXTRA_DIRECTIVES: |
        cors_origins ${MERCURE_CORS_ALLOW_ORIGIN}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/healthz"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - mercure-data-prod:/data
      - mercure-config-prod:/config
    networks: 
      - backend-frontend-bridge