FROM php:8.4-fpm-alpine

WORKDIR /app

ARG DATABASE_URL
ENV DATABASE_URL=DATABASE_URL

RUN apk update && apk add --no-cache \
    git \
    unzip \
    libzip-dev \
    icu-dev \
    postgresql-dev \
    postgresql \
    libsodium-dev \
    && docker-php-ext-configure intl \
    && docker-php-ext-install \
        zip \
        intl \
        pgsql \
        pdo \
        pdo_pgsql \
        sodium

RUN sed -i 's|listen = 127.0.0.1:9000|listen = 0.0.0.0:9000|' /usr/local/etc/php-fpm.d/www.conf

COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

COPY ./build/php.ini /usr/local/etc/php/php.ini

COPY . .

RUN composer install --optimize-autoloader --no-scripts

RUN chown -R www-data:www-data /app

CMD ["php-fpm"]
