nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['http://localhost:5173', '%env(CORS_ALLOW_ORIGIN)%']
        allow_credentials: true
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Link']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        max_age: 3600
    paths:
        '^/': ~
