FROM nginx:alpine

# Copy the public directory from the backend image
COPY --from=quizz-vuejs-backend /app/public /usr/share/nginx/html/backend_public

# Copy our Nginx configuration
COPY nginx-prod.conf /etc/nginx/conf.d/default.conf
