FROM matomo:fpm-alpine

RUN apk --no-cache add nginx

RUN mkdir -p /run/nginx

COPY nginx-dev.conf /etc/nginx/http.d/default.conf

RUN mkdir -p /var/www/html/tmp &&     chown -R www-data:www-data /var/www/html/tmp &&     chmod -R 777 /var/www/html/tmp

CMD ["sh", "-c", "php-fpm & nginx -g 'daemon off;'"]